# Generated by Django 5.0.4 on 2024-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardholder',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='duo',
            name='sport_choice',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='famille',
            name='sport_choice',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='solo',
            name='sport_choice',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
