# Generated by Django 5.0.4 on 2024-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_creditcardholder_total_price_duo_sport_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardholder',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
