# Generated by Django 5.0.4 on 2024-05-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField()),
                ('site', models.TextField()),
                ('sport_date', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='image_sport/')),
            ],
            options={
                'verbose_name': 'Sports',
                'verbose_name_plural': 'Sports',
            },
        ),
    ]
