# Generated by Django 5.0.4 on 2024-04-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sports_date_epreuves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='date_epreuves',
            field=models.TextField(),
        ),
    ]
