# Generated by Django 5.0.4 on 2024-04-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sports_date_epreuves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='date_epreuves',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sports',
            name='site',
            field=models.TextField(),
        ),
    ]
