# Generated by Django 5.0.4 on 2024-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sports_date_epreuves_alter_sports_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
