# Generated by Django 5.0.4 on 2024-04-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_sports_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sports',
            old_name='date_epreuves',
            new_name='sport_date',
        ),
    ]
