# Generated by Django 5.0.4 on 2024-05-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrestickets',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offres_tickets'),
        ),
    ]
